version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: agentichq
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agentichq
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agentichq"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # the Dockerfile you just fixed builds both backend + (optionally) frontend
    build:
      context: .
      target: production          # explicit, in case you later add a dev target
    image: agentichq-app:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://agentichq:password@postgres:5432/agentichq
      PGUSER: agentichq
      PGPASSWORD: password
      PGDATABASE: agentichq
      PGHOST: postgres
      PGPORT: 5432
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
